### ISSUE TITLE
For query attributes that are booleans, preselect the operator to be = and make the value options a drop-down of true, false or asterisk

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#15]
![image](https://cloud.githubusercontent.com/assets/6863908/5784189/84ecde06-9d8f-11e4-9c2f-54f7d4e09f64.png)

**Comment by juliemuraski** [comment]
This will affect the Free Shipping, In Store Availability, Online Availability, On Sale, Preowned fields

**Comment by cmlizama** [comment]
![boolean](https://cloud.githubusercontent.com/assets/5415869/5964493/223989dc-a7ba-11e4-82ff-2b5fca7fbe3f.png)
