### ISSUE TITLE
For query attributes that are numerics for their value entry to be a numeric. This will affect the Customer Review Average, Customer Review Count, Dollar Savings, Percent Savings, Regular Price, Sale Price, Shipping Cost

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#20]

**Comment by cmlizama** [comment]
Cool I think I just realized how to do this. In the config file, each object should have a "type" key and the value will be text, number, etc. Then in the html we can do `type="{{attributeOption.text}}"

**Comment by cmlizama** [comment]
I'll have to think more about how to do the booleans but im pretty sure it's possible.

**Comment by cmlizama** [comment]
![number input](https://cloud.githubusercontent.com/assets/5415869/5964591/07078cbc-a7bb-11e4-8711-ea3f90e075cd.png)
