### ISSUE TITLE
category/attribute/keyword should be shown to be optional

### ISSUE THREAD

**Issue by cmlizama** [BestBuyAPIs/bby-query-mixer#21]
add copy that makes it clear that these are optional, but that at least one of them needs to be chosen

**Comment by juliemuraski** [comment]
Let's confirm the changes we want to make here. I am not 100% that we should force the user to pick query criteria. It is a valid query to submit a request without any criteria although I would question it's usefullness.

**Comment by cmlizama** [comment]
True. I also fixed it so that you can run a request without any criteria and get a list of all products back.

**Comment by juliemuraski** [comment]
Let's wait until we have some user feedback before making building the query more restrictive
