### ISSUE TITLE
Add steps to identify the different parts of creating a request

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#25]

**Comment by juliemuraski** [comment]
![ux_suggestions](https://cloud.githubusercontent.com/assets/6863908/5784984/318dcf74-9d97-11e4-86e7-8329c3056455.png)

**Comment by juliemuraski** [comment]
Please center the numbers in the circle

**Comment by cmlizama** [comment]
Fixed
