### ISSUE TITLE
For the RUN Query, RESET Query buttons change gradient upon hover over box

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#29]

**Comment by cmlizama** [comment]
The buttons change to a light blue at the moment, we should ask for feedback if that is the right behavior we want. We might want a different shade of blue or something.

**Comment by juliemuraski** [comment]
![image](https://cloud.githubusercontent.com/assets/6863908/5904759/809d1b68-a550-11e4-9c82-d68e9b44d7bd.png)

I agree I think this is still subtle but waiting until we confirm changes on developer.bestbuy.com

**Comment by juliemuraski** [comment]
Verified gradient is changing ... If different requirements will create new issue
