### ISSUE TITLE
Feedback from Ira and Anna

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#35]
The only change I see is under Search for Products, I think "a keyword search" would work better as just "a keyword".

Anna Bliss [10:36 AM] 
I agree with @irabrooker on the "a keyword" change. Also, in the Build Your Response - is there room to change the description to read "select the attributes to include..."?

**Comment by juliemuraski** [comment]
Change has been made and pushed into feature/copyUpdatesI7 branch

**Comment by juliemuraski** [comment]
Pending pull request

**Comment by juliemuraski** [comment]
Change 
![image](https://cloud.githubusercontent.com/assets/6863908/6002469/365e1656-aab9-11e4-8a2c-c59869b09e5c.png)

to be 

You can search by one of our more popular categories (https://developer.bestbuy.com/documentation/categories-api), an attribute (https://developer.bestbuy.com/documentation/products-api#documentation/products-api-detail) value, keyword (https://developer.bestbuy.com/documentation#advancedSearch-search) or any combination of these:

**Comment by cmlizama** [comment]
![screen shot 2015-02-02 at 10 17 42 am](https://cloud.githubusercontent.com/assets/5415869/6003887/b9f326b8-aac4-11e4-9291-e30d4695cea2.png)
