### ISSUE TITLE
Add faceting as Build Your Response option

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#36]

**Comment by cmlizama** [comment]
Looks doable but first I think I'll need someone to help me understand the docs for it. So facet takes an attribute and also an integer?

**Comment by cmlizama** [comment]
![facets](https://cloud.githubusercontent.com/assets/5415869/5967140/d6fc61e0-a7cf-11e4-8e41-fe2d76d264cb.png)
