### ISSUE TITLE
Explanation URLs are not showing attributes

### ISSUE THREAD

**Issue by leahdebruycker** [BestBuyAPIs/bby-query-mixer#37]
In sample screen shot below: Manufacturer should be added to the baseURL information.
![screen shot 2015-01-22 at 12 03 13 pm](https://cloud.githubusercontent.com/assets/9833487/5861427/c853bd7e-a22e-11e4-82e5-99dedcdaacd0.png)

**Comment by cmlizama** [comment]
![attribute fix](https://cloud.githubusercontent.com/assets/5415869/5964574/dd92c72a-a7ba-11e4-98b5-f3e0884ffead.png)
