### ISSUE TITLE
Products: increase spacing between True and False on boolean values

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#42]
![image](https://cloud.githubusercontent.com/assets/6863908/5922335/5306a5e6-a610-11e4-8167-1dbc35a0a67b.png)

**Comment by cmlizama** [comment]
![boolean](https://cloud.githubusercontent.com/assets/5415869/5964629/46033ede-a7bb-11e4-9e09-aa810aafb6a5.png)
