### ISSUE TITLE
Recommendations: Update endpoint description

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#44]
UPDATE COPY: The Recommendation Endpoints are a family of endpoints providing access to top trending products and most popular products based on customer behavior at BESTBUY.COM.

**Comment by cmlizama** [comment]
fixed with 1a091e0c10e56d67e52460c8f31d1bd8d8b55e9c
![screen shot 2015-01-29 at 1 36 17 pm](https://cloud.githubusercontent.com/assets/5415869/5964701/d5c305fe-a7bb-11e4-90a2-c099003baf16.png)
