### ISSUE TITLE
Recommendations: "baseURL : https://api.remix.bestbuy.com/v1/products/" is incorrect

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#46]
![image](https://cloud.githubusercontent.com/assets/6863908/5925322/565a680a-a628-11e4-898c-a530d66e5060.png)

**Comment by juliemuraski** [comment]
Should instead be something like "http://api.bestbuy.com/beta/products/trendingViewed"

**Comment by cmlizama** [comment]
![url fix](https://cloud.githubusercontent.com/assets/5415869/5964470/f6aa67e6-a7b9-11e4-9973-e18fbf0d0e39.png)
