### ISSUE TITLE
Add link to Sort By

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#56]
Can we add a link to [Sort By:] to https://developer.bestbuy.com/documentation#sort-sort

![image](https://cloud.githubusercontent.com/assets/6863908/6002592/4a047802-aaba-11e4-87bf-9fc7aa98849d.png)

**Comment by cmlizama** [comment]
![screen shot 2015-02-02 at 1 04 59 pm](https://cloud.githubusercontent.com/assets/5415869/6006920/229d0a5a-aadc-11e4-9a93-323994024231.png)
