### ISSUE TITLE
Can we align the Facets/Sort By section

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#57]
We need the "Choose Attribute and Best Selling Rank" to align. The number also looks a little odd but not sure how to fix it

https://developer.bestbuy.com/documentation#sort-sort

![image](https://cloud.githubusercontent.com/assets/6863908/6002625/ac254570-aaba-11e4-8bb6-1c439ea11222.png)

**Comment by j-bjork** [comment]
![screen shot 2015-02-02 at 9 30 03 am](https://cloud.githubusercontent.com/assets/8552692/6003051/1edbe44a-aabe-11e4-9523-5f066fffdd61.png)

Adding a 4px margin-left to the Facets <a> tag produces a perfect alignment. It's a static fix, but it does the trick.

**Comment by cmlizama** [comment]
![screen shot 2015-02-02 at 10 07 49 am](https://cloud.githubusercontent.com/assets/5415869/6003715/58ace106-aac3-11e4-9244-84b0105a21b7.png)
