### ISSUE TITLE
Add question mark to Facets with following help text

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#58]
Faceting provides an aggregated count of the specified attributes as returned in the results. It will include the number of the aggregated results as specified by number field.

**Comment by cmlizama** [comment]
![screen shot 2015-02-02 at 10 44 54 am](https://cloud.githubusercontent.com/assets/5415869/6006469/37e30a76-aad8-11e4-8dd9-43d5a3fe6df8.png)
