### ISSUE TITLE
Change text in API Key box

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#62]
Change text in the API Key box in query mixer says 'YourAPIGoesHere' to be 'YourAPIKeyGoesHere

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 3 42 22 pm](https://cloud.githubusercontent.com/assets/5415869/6177625/c70cfa84-b2cd-11e4-870f-35bddf973d57.png)

**Comment by juliemuraski** [comment]
Cannot reproduce in production 
![image](https://cloud.githubusercontent.com/assets/6863908/6189414/06e77660-b360-11e4-85cd-0f6cb59a2f8b.png)

**Comment by juliemuraski** [comment]
Verified working in production
![image](https://cloud.githubusercontent.com/assets/6863908/6195254/da4990b6-b391-11e4-9ff9-658e21e3b5cb.png)
