### ISSUE TITLE
If you add a facet but no numerical value you get an error; force entry of numerical value

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#64]

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 4 18 00 pm](https://cloud.githubusercontent.com/assets/5415869/6178256/bff09bd4-b2d2-11e4-8cfa-2cc3c9ba0c4d.png)

**Comment by juliemuraski** [comment]
Cannot reproduce solution in production

**Comment by juliemuraski** [comment]
Should only highlight red to enter a Facet Number if someone selects an attribute to Facet. If Facets is just "Choose Attribute" there is no reason to force them to enter a number or highlight red.

**Comment by juliemuraski** [comment]
Duplicate
