### ISSUE TITLE
Update "URL" description in the Build Your Response to be "Product Detail URL"

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-mixer#65]

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 3 56 32 pm](https://cloud.githubusercontent.com/assets/5415869/6177890/beac5658-b2cf-11e4-9074-d55bfbe74ebc.png)

**Comment by juliemuraski** [comment]
Julie confirmed this is intended behavior
