### ISSUE TITLE
When invalid data value is inputed for an attribute, appropriate query is not generated

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#68]
ex: 
Choose Attribute: Best Selling Rank
value: hjsdhakjdja (expected is numeric)

query generated: https://api.remix.bestbuy.com/v1/products((bestSellingRank=))?apiKey=b6qgvh88dwuc26hssgp2cb4a&callback=JSON_CALLBACK&sort=bestSellingRank.asc&show=sku,name,salePrice&pageSize=10&page=1&format=json

and result set is empty. No error message is generated

expected:https://api.remix.bestbuy.com/v1/products((bestSellingRank=hjsdhakjdja))?apiKey=b6qgvh88dwuc26hssgp2cb4a&callback=JSON_CALLBACK&sort=bestSellingRank.asc&show=sku,name,salePrice&pageSize=10&page=1&format=json

which should result in a response -

error": {
    "code": 400,
    "status": "400 Bad Request",
    "message": "'fflk' is not a valid value for 'bestSellingRank'.  'bestSellingRank' is an integer between 0 and 2147483647",

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 4 13 21 pm](https://cloud.githubusercontent.com/assets/5415869/6178174/1d1a48d8-b2d2-11e4-8073-f85f9087699c.png)

**Comment by juliemuraski** [comment]
Cannot reproduce fix and also notice after running query one time added garbage to value field of BestSellingRank= and that garbage was not passed forward

**Comment by Sree40** [comment]
Fix is reproducible in production.Closing the issue
