### ISSUE TITLE
sku in <list of SKUs> is not generating correct query

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#72]
when we select the attribute as SKU and operator "in" with the list of SKUs in the value, incorrect query is generated. Basically, a parenthesis  is missing.

Below is the query generated - 
https://api.remix.bestbuy.com/v1/products((sku in 9210023,7640035)&(categoryPath.id=pcmcat209400050001))?apiKey=b6qgvh88dwuc26hssgp2cb4a&callback=JSON_CALLBACK&sort=bestSellingRank.asc&show=sku,name,salePrice&pageSize=10&page=1&format=json

it should be  (sku in (9210023,7640035)

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 3 36 31 pm](https://cloud.githubusercontent.com/assets/5415869/6177505/02ac8e16-b2cd-11e4-9626-15dbbe407334.png)

**Comment by juliemuraski** [comment]
Cannot reproduce fix in production

**Comment by Sree40** [comment]
fix is not reproducible in production.

**Comment by juliemuraski** [comment]
Resolved

![image](https://cloud.githubusercontent.com/assets/6863908/6274641/7e24f2f6-b83e-11e4-9f53-67dc944ad927.png)
