### ISSUE TITLE
Selecting value=* for attributes like onsale, online Availability etc is generating incorrect queries

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#73]
Ex:  - Select onSale as the attribute and "=" as the operator and "*" from the drop down for value
       - Invalid query is built out of the above selection. This is happening for all the attributes with "*" in the drop down.

Below is the query generated - 

https://api.remix.bestbuy.com/v1/products((inStoreAvailability=[object Object])&(categoryPath.id=pcmcat209400050001))?apiKey=b6qgvh88dwuc26hssgp2cb4a&callback=JSON_CALLBACK&sort=bestSellingRank.asc&show=sku,name,salePrice&pageSize=10&page=1&format=json

(inStoreAvailability=[object Object]) should be  (inStoreAvailability=*)

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 1 03 52 pm](https://cloud.githubusercontent.com/assets/5415869/6174880/a8ec6564-b2b7-11e4-8eb3-49fe3dd93d56.png)

**Comment by juliemuraski** [comment]
Cannot reproduce in production
![image](https://cloud.githubusercontent.com/assets/6863908/6189546/18b05870-b361-11e4-8ce2-4619d8e114c2.png)

**Comment by Sree40** [comment]
Fix is reproducible in production.Closing the issue
