### ISSUE TITLE
Enhancement req: In " Build Your Response" an option to select all and unselect all the attributes will be handy

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#74]
When trying to select all the attributes or unselect the selected, one should manually check the checkbox for every attribute. It would be handy to have a check box for select/unselect all

**Comment by juliemuraski** [comment]
Can reproduce in production 

![image](https://cloud.githubusercontent.com/assets/6863908/6261797/4925b064-b7bb-11e4-91d0-607487ee8138.png)
