### ISSUE TITLE
Recommendations UI is missing reference to the API documentation

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#75]

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 3 50 15 pm](https://cloud.githubusercontent.com/assets/5415869/6177774/de77ef7a-b2ce-11e4-80ad-e5e9aab4ce23.png)

**Comment by juliemuraski** [comment]
Cannot reproduce in production

**Comment by Sree40** [comment]
Fix is reproducible in production.Closing the issue
