### ISSUE TITLE
Category name is not completely matching the name returned by categories API

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#76]
For the category id # pcmcat310200050004,  name returned by the API is "Portable & Wireless Speakers". 
Query builder is displaying as "Portable Speakers,Docks & Radios.

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 4 24 49 pm](https://cloud.githubusercontent.com/assets/5415869/6178355/ba1a3d04-b2d3-11e4-9494-1e4aae6ebb40.png)

**Comment by juliemuraski** [comment]
Cannot reproduce in production
![image](https://cloud.githubusercontent.com/assets/6863908/6189479/91360142-b360-11e4-8b63-1ef6fe730870.png)

**Comment by Sree40** [comment]
Fix is reproducible in production.Closing the issue
