### ISSUE TITLE
Open box query builder doesn't have reference to open box documentation 

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#77]

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 3 54 10 pm](https://cloud.githubusercontent.com/assets/5415869/6177851/7c0eb28c-b2cf-11e4-92a7-960d12985b4b.png)

**Comment by juliemuraski** [comment]
Cannot reproduce in production
![image](https://cloud.githubusercontent.com/assets/6863908/6189459/66739ce4-b360-11e4-966d-3614b948ebbb.png)

**Comment by juliemuraski** [comment]
Confirmed links are correct
