### ISSUE TITLE
Error code 400 has to be returned, when invalid size is provided as imput

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#78]
Results per page can be anywhere between 1 and 100, if an invalid value is provided as input (like "101 "or "dfsjnf") query is generated with the parameter value as undefined and a 404 is returned.

Instead, 400 has to be returned.

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 3 45 22 pm](https://cloud.githubusercontent.com/assets/5415869/6177721/6cb70d62-b2ce-11e4-8db3-dd2ea3101f97.png)

**Comment by juliemuraski** [comment]
Are they any options for telling the user that they cannot request more than 100 pages?

**Comment by juliemuraski** [comment]
Comments from Remix explain issue...suggest we use that instead
