### ISSUE TITLE
Right parenthesis is missing in the query for open box offers by List of SKUs.

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#79]
Incorrect query is generated, when querying for the open box offers by a list of SKUs

http://api.bestbuy.com/beta/products/openBox(sku%20in(23235265,3822987)?apiKey=rbda762vjychtktzbj8kdcn4&callback=JSON_CALLBACK&pageSize=10&page=1

Right parenthesis is missing - (sku%20in(23235265,3822987)

should be (sku%20in(23235265,3822987))

**Comment by cmlizama** [comment]
![screen shot 2015-02-12 at 3 59 45 pm](https://cloud.githubusercontent.com/assets/5415869/6177950/44124f00-b2d0-11e4-886d-64eb7591bd18.png)

**Comment by juliemuraski** [comment]
Tested and resolution passed 

![image](https://cloud.githubusercontent.com/assets/6863908/6218023/8c614240-b5df-11e4-96cc-2801d8f23a7d.png)
