### ISSUE TITLE
Store services "select all" is generating a 404 response

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#81]
Invalid query is generated, when I try query for a store with "Select All" for store services

**Comment by cmlizama** [comment]
It seems to break on any service value that has an '&' in it

**Comment by cmlizama** [comment]
With no location/store search criteria:
![screen shot 2015-02-13 at 12 51 34 pm](https://cloud.githubusercontent.com/assets/5415869/6193267/15259724-b37f-11e4-8c92-ec1678a03588.png)

with store/location search criteria:
![screen shot 2015-02-13 at 12 52 31 pm](https://cloud.githubusercontent.com/assets/5415869/6193278/334a1c7a-b37f-11e4-9518-6244e2d188c3.png)

**Comment by juliemuraski** [comment]
There are no results but the query works as intended

![image](https://cloud.githubusercontent.com/assets/6863908/6216188/229196a6-b5cd-11e4-9658-c38c03dfd98d.png)
