### ISSUE TITLE
Incorrect attribute name is displayed, while building query with long, lat

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#90]
Attribute names should be Latitude, Longitude, and Radius (But not area)

**Comment by juliemuraski** [comment]
![image](https://cloud.githubusercontent.com/assets/6863908/6237591/d6f02b0c-b6b9-11e4-84a0-e51086e610f0.png)

**Comment by juliemuraski** [comment]
Resolved

![image](https://cloud.githubusercontent.com/assets/6863908/6274376/d0e24112-b83c-11e4-8a66-761adf89f281.png)

![image](https://cloud.githubusercontent.com/assets/6863908/6274395/efb31a80-b83c-11e4-8e4c-bd008db75058.png)
