### ISSUE TITLE
Long, lat and area/radius values, has a limit on the length of the numeric inputed

### ISSUE THREAD

**Issue by Sree40** [BestBuyAPIs/bby-query-mixer#92]
If we input long attribute, with a 3 digit number - long is left blank in the query 
If we input lat attribute, with a 4 digit number - lat is left blank in the query 
If we input area attribute, with a 4 digit number - area is left blank in the query

**Comment by juliemuraski** [comment]
Will leave this validation to the user and also to Remix. Choosing not to add it to QB.
